* Medellín contexto rico y complejo para la cultura
* Por Marta Salazar Jaramillo                                       :autores:
** Contexto                    :cooperacion_internacional:contexto:medellin:
Medellín creó en el 2002 la Secretaría de Cultura Ciudadana.<2002-01-01 Sun> Este hecho se considera un parteaguas en la dinámica de los procesos culturales en la Ciudad. Recurriendo a  la historia más cercana, los años 80 y 90 fueron como un infierno para Medellín. El narcotráfico rampante por la ciudad impuso el miedo. El toque de queda hizo que la ciudad de noche pareciera muerta. A la par que se gestaba esa ola de violencia, también emergieron procesos culturales en su mayoría de corte comunitario, que empezaron a proponer otra forma de vivir, de relacionarnos; los habitantes no se resignaron al regimen del terror y propusieron otras dinámicas para esta urbe. Estos esfuerzos individuales y colectivos llevaron a la ciudad a otro ritmo, a reconocer que aquí vivía la  guerra,  pero también habitaba la esperanza.

El trabajo cultural en su mayoría era realizado con recursos propios de las organizaciones y también con cooperación internacional que había llegado con el llamado boom de  los sicarios de las comunas. El Estado participaba poco en los procesos que se estaban gestando. El movimiento académico y de las ONG fue tomando fuerza y a partir de este cambio, el Municipio también hizo un giro en la mirada.
** Una ciudad…                         :medellin:historia:topografia:musica:

La historia de Medellín como ciudad es muy reciente, apenas en el siglo pasado empieza a configurarse como tal, debido a la llegada de empresas que se instalaron en la ciudad. Pasó en muy pocos años de ser una Villa a una pequeña urbe con más de 500 mil habitantes. Este proceso se vivió con la llegada principalmente de personas del campo a la ciudad a trabajar en las fábricas como obreros. Se fue construyendo una ciudad planeada y pensada y otra  que  se podría llamar improvisada, con la personas que  querían tener un  empleo, mejorar su calidad de vida y se fueron asentando en las laderas de las montañas. También la llegada de nuevos ciudadanos estuvo marcada por la Violencia en el campo entre conservadores y liberales y después a finales del siglo pasado por la guerra entre paramilitares, guerrilla y ejército. Creció la urbe y ahora tiene más de 2.300.000 habitantes según el último censo. Una mezcla de culturas se instaló en la ciudad.

La topografía de Medellín es particular, es un cañón de un río con montañas muy altas y verdes. El clima hace que tengamos una ciudad con flores todo el tiempo; esta costumbre viene de las prácticas campesinas que se instalaron en la ciudad durante todo  el  siglo pasado. Asimismo, otras formas de contar la historia  como  la  trova,  la  música,  el  baile entre otras expresiones conocidas como populares, marcan y definen unas características de nuestra cultura.

A la par que se configuraba la ciudad con los campesinos, también lo hacía la ciudad “culta” de una élite de empresarios que tenían contacto con el resto del mundo.  Se  abrieron galerías de arte y se realizaron eventos como por ejemplo la bienal de Coltejer, reconocida en el mundo por su impacto en las artes plásticas de latinoamérica.

Medellín vivió todo el apogeo de la revolución industrial. Paisajes urbanos que muestran los  vestigios  de  todas  las  empresas  que  existieron,  transformados  la  mayoría  en  los
últimos años en lugares para vivienda.  Las  universidades  crearon  las  facultades  de ingeniería para responder a ese llamado. En 1887 nace la Facultad de Minas de la Universidad Nacional de Colombia, dedicada al pensamiento y la técnica de la ingeniería. Paralelo el valle se iba transformando para que llegara la industria, un ejemplo que transformó el ambiente de manera radical fue la canalización del Río Medellín; transformaron los meandros y el movimiento en una línea recta, que tendría a los lados a las principales empresas. Menciono estos hechos porque han sido determinantes en la construcción de los imaginarios de la cultura en la ciudad, es decir, la importancia de la ingeniería por sobre todas las cosas en esta Medellín extrema.

Medellín es una ciudad grande, es la tercera por habitantes en Colombia pero la primera en muchos aspectos:  infraestructura,  servicios,  empresas,  universidades;  en  todo  lo técnico es una urbe preparada para la competitividad. En este lugar sin embargo, existe una debilidad, vista por los ojos extranjeros como problemática y es el poco  acceso  a eventos culturales.  Esta situación se ha ido revirtiendo poco a poco con la construcción especialmente de infraestructura pública, la revitalización de los Museos con los que se contaba y la creación de nuevos escenarios públicos y privados para la promoción y circulación de las artes. Nos encontramos en un momento complejo, en el que como en los 80, se empieza a gestar un nuevo momento para la cultura.

Dos mundos, Medellín es una ciudad de contrastes. Dos formas de vivir que coexisten en este mismo cañón. Prueba de ello es por un lado:  “El  programa  Medellín  Cómo  Vamos señala que de los 2 millones 368 mil habitantes que tiene la ciudad, 213 mil personas (con las que se puede llenar cinco veces el estadio Atanasio Girardot), es decir el 9 por ciento, viven en condiciones de pobreza extrema. Otros 468 mil (el 22 por ciento) viven en situación de pobreza” (Periódico El Colombiano, 11 de mayo 2012). Pero también nos encontramos con barrios de la ciudad en le que las personas tienen todas sus necesidades básicas satisfechas y su índice de calidad de vida es igual a los de Estocolmo.
** Cambiando  tendencias                    :medellin:teatro:comportamiento:

¿Qué hace que una persona tome la decisión de ir a un Teatro? Esa es la pregunta que nos hacemos todos los días los que estamos vinculadas con el mundo de las artes escénicas en Medellín. La ciudad cuenta con más de 27 teatros de diferentes tamaños dedicados a presentar obras propias y ajenas. En el último año dos teatros decidieron cerrar.  El silencio del público los llevó a retirarse del escenario. A pesar de no contar con cifras estadísticas en el sector, el rumor si está y es contundente, la gente en Medellín no está yendo a ver obras de teatro. Bueno también debo hacer una salvedad, si la obra es hecha por personajes famosos de televisión o si es de humor, la tendencia es distinta.

Los teatros de la ciudad sobreviven  con  recursos  propios,  presentaciones  privadas, festivales y apoyos concertados con Alcaldía y Ministerio de Cultura. La facultad de Teatro de la Universidad de Antioquia sigue graduando personas profesionales en teatro.  A  los teatros no les alcanzan los recursos que perciben para hacer nuevos montajes, pagar a los actores y otras personas que se requiera, cubrir los costos fijos de las sedes. Este asunto parece en círculo vicioso y sin salida. Se debe encontrar un punto en  el  que  se  pueda revertir la situación, pasar de la supervivencia a la sostenibilibad de cada uno de los escenarios.






